"use client";

/**
 * Meta pixel — marketing pages only, never the logged-in product.
 *
 * WHY THIS IS SCOPED AND NOT JUST DROPPED IN THE ROOT LAYOUT
 * ----------------------------------------------------------
 * #538 put the base pixel straight in the root layout, which is the only
 * layout carrying <html>. That means it would have run on `/app/*` too — the
 * entire logged-in surface, including `/app/ticker/[symbol]`.
 *
 * That matters more here than on a normal SaaS. Meta's `fbevents.js` reports
 * the FULL current URL as the `dl` parameter on its `/tr/` beacon. `dl` is a
 * payload field, not the Referer header, so our
 * `Referrer-Policy: strict-origin-when-cross-origin` (next.config.js) does not
 * trim it. And because `/tr/` is on facebook.com, the browser attaches
 * whatever facebook.com cookies it already holds. Net effect, once the pixel
 * is switched on: **which specific tickers a user researches, linkable to
 * their real Facebook account.** For a financial product that is a serious
 * disclosure to make by accident.
 *
 * Nothing is lost by scoping it. The pixel's job is ad attribution, which
 * happens on acquisition pages. StartTrial and Purchase are sent SERVER-SIDE
 * by `services/meta_capi`, which needs no browser at all and survives
 * ad-blockers — and they have to be, since one happens inside `/app` and the
 * other arrives on a Stripe webhook 14 days later with no browser in the
 * picture. So the logged-in surface has nothing to contribute and everything
 * to leak.
 *
 * CompleteRegistration is the ONE exception, and it is deliberate.
 * `lib/metaConversions.ts` also fires it from the browser at the moment signup
 * succeeds — on `/signup`, inside the allowed scope, never on `/app`. This
 * paragraph used to say every conversion was server-side only; that was true
 * as written and wrong in effect, because `meta_capi` is gated on a
 * Conversions API token that was never set. The result only surfaced once the
 * paid burst was live and spending: Events Manager held exactly one event for
 * the dataset, `PageView`, while the ad set optimised toward
 * CompleteRegistration.
 *
 * The two copies share a deterministic `event_id` (`meta_capi.event_id_for`,
 * mirrored in `lib/metaConversions.ts` and pinned by
 * `__tests__/metaConversions.test.ts` against fixtures generated by the Python
 * side). Meta de-duplicates on (event_name, event_id), so today the browser is
 * the only sender, and the day the token is set the two collapse into one
 * conversion rather than double-counting. That distinction is load-bearing:
 * cost-per-registration is the pre-committed kill criterion for the burst.
 *
 * HONEST LIMIT OF THIS CONTROL
 * ----------------------------
 * This prevents the script from ever being INSERTED on an `/app/*` page. It
 * does not unload it if the user client-side-navigates from a marketing page
 * into `/app` in the same tab — once `fbevents.js` is in the document it stays
 * there. No new PageView is sent (we only fire one at init, and the base pixel
 * does not auto-track SPA route changes), but the script is present. A hard
 * navigation or fresh load of any `/app/*` URL — the common case for a
 * logged-in user, who lands there by bookmark or redirect — gets no pixel at
 * all. Stated plainly rather than overclaimed, because the privacy policy
 * describes this behaviour and must not describe it as airtight.
 *
 * A SEPARATE RISK THIS FILE CANNOT CONTROL
 * ----------------------------------------
 * Meta's **Automatic Advanced Matching** is a per-pixel toggle in Events
 * Manager. Turning it on makes `fbevents.js` scrape visible form fields —
 * email, phone, name — and send hashed values, with no change to this repo.
 * We deliberately pass no advanced-matching object to `fbq('init', ...)`, but
 * that toggle overrides intent from the dashboard. Leave it OFF. See
 * `docs/META_GO_LIVE.md`.
 */

import Script from "next/script";
import { usePathname } from "next/navigation";

/** Route prefixes the pixel must never load on. */
const EXCLUDED_PREFIXES = ["/app"] as const;

export function isPixelAllowedPath(pathname: string | null): boolean {
  if (!pathname) return false;
  return !EXCLUDED_PREFIXES.some(
    (p) => pathname === p || pathname.startsWith(`${p}/`),
  );
}

export function MetaPixel({ pixelId }: { pixelId: string }) {
  const pathname = usePathname();

  // No id → the pixel does not exist at all. This is the production state
  // until the operator sets NEXT_PUBLIC_META_PIXEL_ID as a BUILD ARG (a Fly
  // secret of that name is a no-op — the value is inlined at build time).
  if (!pixelId) return null;
  if (!isPixelAllowedPath(pathname)) return null;

  return (
    <Script
      id="meta-pixel"
      strategy="afterInteractive"
      dangerouslySetInnerHTML={{
        __html: `
          !function(f,b,e,v,n,t,s)
          {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
          n.callMethod.apply(n,arguments):n.queue.push(arguments)};
          if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
          n.queue=[];t=b.createElement(e);t.async=!0;
          t.src=v;s=b.getElementsByTagName(e)[0];
          s.parentNode.insertBefore(t,s)}(window,document,'script',
          'https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '${pixelId}');
          fbq('track', 'PageView');
        `,
      }}
    />
  );
}
