/**
 * Web app manifest — the missing half of the web-push story.
 *
 * WHY THIS IS NOT COSMETIC
 * ------------------------
 * `app/app/billing/page.tsx` tells customers, on the paid-upgrade page:
 *
 *     "Lock-screen notifications on desktop and Android.
 *      iOS requires the PWA to be installed."
 *
 * and `lib/webPush.ts` documents the same constraint from the code side:
 *
 *     "iOS Safari note: only works on installed PWAs (16.4+). Will throw on
 *      non-installed iOS Safari."
 *
 * Both were true. What was missing was any way to *install* the PWA: there was
 * no manifest at all (GET /manifest.webmanifest returned 404, and no
 * <link rel="manifest"> was ever emitted), so on iOS "Add to Home Screen"
 * produced a Safari bookmark rather than a web app, and `display` fell back to
 * `browser`. A bookmark cannot register for push. So the billing page was
 * selling an iOS capability that could not be reached — audited 2026-08-29.
 *
 * `display: "standalone"` is the load-bearing field: iOS only grants the Push
 * API to a Home Screen web app running standalone.
 *
 * `start_url` is /app rather than / on purpose — someone who installs the app
 * wants the scanner, not the marketing landing page. Unauthenticated visitors
 * are redirected to /signin by middleware, which is the correct first screen
 * for a fresh install anyway.
 */
import type { MetadataRoute } from "next";

export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Tapeline — quantitative market scanner",
    short_name: "Tapeline",
    description:
      "One score per US ticker from six named factors, with a daily back-checked public track record.",
    start_url: "/app",
    scope: "/",
    display: "standalone",
    // Matches the themeBootScript default and favicon.svg background, so the
    // splash screen does not flash a different colour before first paint.
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    orientation: "portrait-primary",
    categories: ["finance", "business", "productivity"],
    icons: [
      // Generated by app/icon.tsx. "any maskable" lets Android crop to its
      // own shape without letterboxing; the mark is centred with enough
      // padding to survive the safe-zone crop.
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
