/**
 * Per-ticker SEO landing pages at /blog/ticker/{SYMBOL}.
 *
 * One template serves 50 posts (manifest at app/blog/ticker/tickers.ts,
 * generated by scripts/generate-ticker-posts.mjs). Each post:
 *   - Targets long-tail queries like "{SYMBOL} stock score 2026" and
 *     "is {SYMBOL} a buy".
 *   - Pulls live score + 6-factor breakdown + plain-English reason from
 *     /api/ticker/{symbol} at request time, with Next.js revalidate
 *     caching so we're not hammering the API on every crawler hit.
 *   - Links into /t/{symbol} for the interactive product surface and
 *     /scorecard for the public back-check.
 *
 * Distinct from /t/[symbol]: that page is the interactive product surface
 * (watchlist add, share, OG card). This page is long-form editorial with
 * scoring methodology context — same data, different SERP intent.
 */
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarketingNav } from "@/components/MarketingNav";
import { MarketingFooter } from "@/components/MarketingFooter";
import { NewsletterCapture } from "@/components/NewsletterCapture";
import { pageMeta } from "@/lib/seo";
import { articleJsonLd, breadcrumbJsonLd, faqJsonLd, jsonLdScript } from "@/lib/jsonld";
import { TICKERS, findTicker, type TickerPost } from "../tickers";

// Refresh per-page live data every 30 minutes. Long-tail SEO pages don't
// need sub-minute freshness; longer cache = fewer API hits on each crawl.
export const revalidate = 1800;

const API_BASE =
  process.env.NEXT_PUBLIC_API_URL ||
  process.env.API_URL ||
  "https://api.tapeline.io";

type FactorEntry = { value: number | null; weight: number; label: string };

type TickerData = {
  symbol: string;
  name: string;
  sector: string | null;
  price: number | null;
  score: number | null;
  signal: string | null;
  confidence_pct: number | null;
  change_pct_1d: number | null;
  change_pct_5d: number | null;
  change_pct_1m: number | null;
  reason: string | null;
  breakdown?: {
    trend?: FactorEntry;
    rs?: FactorEntry;
    fundamentals?: FactorEntry;
    smart_money?: FactorEntry;
    macro?: FactorEntry;
    momentum?: FactorEntry;
  };
};

async function fetchTicker(symbol: string): Promise<TickerData | null> {
  try {
    const res = await fetch(`${API_BASE}/api/ticker/${symbol}`, {
      next: { revalidate: 1800 },
    });
    if (!res.ok) return null;
    return (await res.json()) as TickerData;
  } catch {
    return null;
  }
}

// Per-ticker scorecard track record. Pulled at render time so each
// /blog/ticker/{X} page can show its OWN historical hit rate + best/
// worst alpha day — substantially distinct content from /t/{X} (which
// only shows live data, no historical aggregates).
type ScorecardForSymbol = {
  symbol: string;
  in_universe: boolean;
  appearances: number;
  appearances_scored: number;
  entries_excluded_outliers: number;
  median_1d_return: number | null;
  median_alpha_vs_spy: number | null;
  hit_rate_beat_spy: number | null;
  best_alpha: number | null;
  worst_alpha: number | null;
};

async function fetchSymbolScorecard(symbol: string): Promise<ScorecardForSymbol | null> {
  try {
    const res = await fetch(`${API_BASE}/api/scorecard/symbol/${symbol}`, {
      next: { revalidate: 3600 }, // hourly is plenty — scorecard rolls daily
    });
    if (!res.ok) return null;
    const body = (await res.json()) as { summary: ScorecardForSymbol };
    return body.summary;
  } catch {
    return null;
  }
}

// Signal-specific narrative paragraphs. Each signal label maps to a
// 2-3 sentence explanation of what the score implies for action. The
// final string interpolates {SYMBOL} so each /blog/ticker/{X} page
// gets prose tied to its current label — substantially-unique content
// across the 50-ticker set.
function signalNarrative(symbol: string, signal: string | null, composite: number | null): string {
  if (!signal || composite === null) {
    return (
      `${symbol}'s composite is currently pending — the worker may be ` +
      `mid-tick, or vendor data may be transiently incomplete. The page ` +
      `refreshes every 30 minutes; if this persists more than an hour the ` +
      `/status page will report the source-feed gap.`
    );
  }
  switch (signal) {
    case "HIGH CONVICTION":
      return (
        `A HIGH CONVICTION reading on ${symbol} (composite ${composite.toFixed(1)}) ` +
        `means all six factor sub-scores are aligned in the same direction with ` +
        `material weight — no single factor is carrying the call. Historically, ` +
        `this label triggers when Trend, Relative Strength, and at least two of ` +
        `Fundamentals/Smart Money/Macro all clear their respective thresholds ` +
        `for confluence. It's the most-restricted label in the Tapeline taxonomy; ` +
        `roughly the top 1-2% of names on any given session earn it.`
      );
    case "STRONG SETUP":
      return (
        `STRONG SETUP on ${symbol} (composite ${composite.toFixed(1)}) means ` +
        `four or more factor sub-scores point the same direction with material ` +
        `weight, but one or two are dragging — usually Macro in a hostile regime ` +
        `or Fundamentals on a name that's growth-y but unprofitable. The setup ` +
        `is structurally bullish but lacks the full-confluence backing of a ` +
        `HIGH CONVICTION read. Treat it as a "primary trend in place" signal.`
      );
    case "CONSTRUCTIVE":
      return (
        `CONSTRUCTIVE on ${symbol} (composite ${composite.toFixed(1)}) means the ` +
        `weighted factor balance leans positive but the confluence is mixed — ` +
        `typically three factors agreeing, two neutral, one against. It's the ` +
        `middle-ground label: enough signal to be on a watchlist, not enough ` +
        `for high-conviction sizing. Pair it with the factor breakdown below to ` +
        `see which sub-scores are doing the lifting.`
      );
    case "NEUTRAL":
      return (
        `NEUTRAL on ${symbol} (composite ${composite.toFixed(1)}) means the six ` +
        `factor sub-scores are split — some bullish, some bearish, no clear ` +
        `aggregate read. This is the most-common label in the universe at any ` +
        `given time (roughly 40-50% of scored tickers). It doesn't mean "do ` +
        `nothing"; it means the model can't tell you what to do, which is honest.`
      );
    case "CAUTION":
      return (
        `CAUTION on ${symbol} (composite ${composite.toFixed(1)}) means the ` +
        `weighted factor balance leans negative — typically Trend or Relative ` +
        `Strength have rolled over while Macro has weakened. It's the inverse ` +
        `of CONSTRUCTIVE: enough signal to flag, not enough to put a clear short ` +
        `framing on. Check the factor breakdown for which sub-scores are dragging.`
      );
    case "WEAK":
      return (
        `WEAK on ${symbol} (composite ${composite.toFixed(1)}) means four or ` +
        `more factor sub-scores point bearishly with material weight. It's the ` +
        `inverse of STRONG SETUP — structurally bearish, but not the full-six ` +
        `confluence that would push it deeper. For long-only investors, this is ` +
        `the "actively avoid" label, not just the "ignore" label.`
      );
    default:
      return (
        `${symbol}'s current signal label is ${signal} (composite ${composite.toFixed(1)}). ` +
        `See the factor breakdown below to inspect what's driving the call.`
      );
  }
}

// Confidence pct interpretation, derived from the value itself. High
// confidence (>= 85) implies full data coverage across all six factor
// inputs — typical for mega-caps. Low confidence (<= 55) implies sparse
// Fundamentals or Smart Money coverage — typical for micro-caps,
// recent IPOs, or sector-specific data gaps (biotech clinical-stage,
// ETFs, foreign ADRs).
function confidenceContext(symbol: string, conf: number | null): string {
  if (conf === null) {
    return (
      `Confidence isn't computed for ${symbol} on this read — the upstream ` +
      `data-coverage signal is pending. The page refreshes hourly.`
    );
  }
  if (conf >= 85) {
    return (
      `${symbol}'s ${Math.round(conf)}% confidence reflects near-full data ` +
      `coverage across the six factor inputs — Trend + RS pull from real ` +
      `historical bars, Fundamentals from a third-party data feed quarterly statements, Smart ` +
      `Money from SEC Form 4 + Congressional disclosures, Macro from a public macro feed, ` +
      `Momentum from primary OHLCV. The composite is as well-informed as the ` +
      `data plumbing allows for a US-listed equity at this scale.`
    );
  }
  if (conf >= 70) {
    return (
      `${symbol}'s ${Math.round(conf)}% confidence reflects strong-but-not-` +
      `complete coverage. Typical gap: Smart Money data may be lighter (fewer ` +
      `recent Form 4 filings or no Congressional disclosures), or Fundamentals ` +
      `may lag the latest quarter. The composite is reliable but tilted slightly ` +
      `toward the always-present Trend/RS/Momentum factors.`
    );
  }
  if (conf >= 55) {
    return (
      `${symbol}'s ${Math.round(conf)}% confidence reflects partial coverage. ` +
      `This is typical for mid- and small-caps: Fundamentals data may be ` +
      `quarter-old, Smart Money has thinner signal density, and 90-day insider ` +
      `flow may be zero. The composite is computed from the available inputs ` +
      `but weighted more heavily toward price-action factors than for a mega-cap.`
    );
  }
  return (
    `${symbol}'s ${Math.round(conf)}% confidence reflects sparse coverage — ` +
    `typically a micro-cap, recent IPO, ETF (no traditional Fundamentals), or ` +
    `sector-specific data gap (biotech clinical-stage names, foreign ADRs). The ` +
    `composite still ranks ${symbol} but the underlying signal is weighted ` +
    `toward Trend / RS / Momentum, the three factors that don't require ` +
    `quarterly statements or insider filings to compute.`
  );
}

// Build every URL at build time so Google can find them on a normal crawl
// rather than needing a deep-link discovery pass.
export function generateStaticParams() {
  return TICKERS.map((t) => ({ symbol: t.symbol }));
}

export async function generateMetadata({ params }: { params: Promise<{ symbol: string }> }) {
  const { symbol } = await params;
  const t = findTicker(symbol);
  if (!t) {
    return pageMeta({
      title: "Ticker not found — Tapeline",
      description: "This per-ticker analysis page no longer exists or has moved.",
      path: `/blog/ticker/${symbol}`,
    });
  }
  return pageMeta({
    title: `Is ${t.symbol} a Buy in 2026? The Tapeline Score Breakdown`,
    description:
      `Live Tapeline 6-factor score on ${t.symbol} (${t.name}) — composite, ` +
      `signal label, Trend / Relative Strength / Fundamentals / Smart Money / ` +
      `Macro / Momentum sub-scores, plain-English reason, and the public ` +
      `scorecard's track record. Same formula, every ticker, every day.`,
    path: `/blog/ticker/${t.symbol}`,
    ogType: "article",
    publishedTime: "2026-05-14",
  });
}

const SIGNAL_COLOR: Record<string, string> = {
  "HIGH CONVICTION": "text-up",
  "STRONG SETUP": "text-up",
  "CONSTRUCTIVE": "text-fg",
  "NEUTRAL": "text-muted",
  "CAUTION": "text-warn",
  "WEAK": "text-down",
};

function fmtScore(v: number | null | undefined): string {
  return v === null || v === undefined ? "—" : v.toFixed(1);
}

function fmtFactor(v: number | null | undefined): string {
  return v === null || v === undefined ? "—" : Math.round(v).toString();
}

function FactorRow({ label, factor, why }: { label: string; factor: FactorEntry | undefined; why: string }) {
  const v = factor?.value;
  const weight = factor?.weight ?? 0;
  return (
    <div className="py-4">
      <div className="flex items-baseline justify-between gap-4">
        <div className="text-base font-medium">{label} <span className="text-xs text-muted">· {weight}% weight</span></div>
        <div className="font-mono text-xl font-bold nums">{fmtFactor(v)}</div>
      </div>
      <p className="mt-1 text-sm text-muted leading-relaxed">{why}</p>
    </div>
  );
}

export default async function TickerBlogPost({ params }: { params: Promise<{ symbol: string }> }) {
  const { symbol } = await params;
  const t = findTicker(symbol);
  if (!t) notFound();

  // Parallel-fetch live data + per-ticker scorecard track record so
  // the page renders the symbol's actual historical hit rate (unique
  // per ticker, not just a generic "we have a scorecard" link).
  const [data, scorecard] = await Promise.all([
    fetchTicker(t.symbol),
    fetchSymbolScorecard(t.symbol),
  ]);

  const composite = data?.score ?? null;
  const signal = data?.signal ?? null;
  const reason = data?.reason ?? null;
  const confidence = data?.confidence_pct ?? null;
  const signalClass = signal ? (SIGNAL_COLOR[signal] ?? "text-fg") : "text-muted";

  // Cached strings used by the new content sections — each is unique per
  // {symbol, signal, composite, confidence} combination, which is the
  // distinguishing payload Google needs to see vs the /t/{symbol}
  // interactive page (same data, different prose framing).
  const narrative = signalNarrative(t.symbol, signal, composite);
  const confidenceText = confidenceContext(t.symbol, confidence);

  const articleUrl = `https://tapeline.io/blog/ticker/${t.symbol}`;
  const article = articleJsonLd({
    title: `Is ${t.symbol} a Buy in 2026? The Tapeline Score Breakdown`,
    description: `Live Tapeline 6-factor score on ${t.symbol} (${t.name}) with full sub-score breakdown and methodology.`,
    url: articleUrl,
    publishedAt: "2026-05-14T00:00:00Z",
    author: "Tapeline",
    // Dynamic per-ticker OG card unlocks Article rich-result image variant.
    // Same source the page's og:image header already points at.
    imageUrl: `https://tapeline.io/blog/ticker/${t.symbol}/opengraph-image`,
  });
  const breadcrumbs = breadcrumbJsonLd([
    { name: "Tapeline", url: "https://tapeline.io/" },
    { name: "Blog", url: "https://tapeline.io/blog" },
    { name: `${t.symbol} score`, url: articleUrl },
  ]);
  const faq = faqJsonLd([
    {
      q: `What is ${t.symbol}'s Tapeline score?`,
      a:
        composite !== null
          ? `${t.symbol} (${t.name}) currently scores ${composite.toFixed(1)} out of 100 on Tapeline's 6-factor composite — signal label "${signal ?? "—"}". The score updates every minute during US market hours.`
          : `${t.symbol} (${t.name}) is in Tapeline's scoring universe. The composite score is computed from six weighted factors and updates every minute during US market hours.`,
    },
    {
      q: `How is the ${t.symbol} score calculated?`,
      a:
        `Tapeline uses one fixed formula for every ticker: 25% trend + 20% relative strength + 15% fundamentals + 15% smart money + 15% macro + 10% momentum. The weights are public, versioned, and don't change without a changelog entry.`,
    },
    {
      q: `Is the ${t.symbol} Tapeline score a buy recommendation?`,
      a:
        `No. The score is descriptive, not prescriptive — it summarizes six independent signals into one 0-100 number. Acting on it depends on portfolio, risk tolerance, time horizon, and tax situation Tapeline doesn't know about.`,
    },
    {
      q: `Where can I see Tapeline's track record on ${t.symbol}?`,
      a:
        scorecard && scorecard.appearances > 0
          ? `${t.symbol} has been in Tapeline's top-10 cohort ${scorecard.appearances} time${scorecard.appearances === 1 ? "" : "s"} since the public scorecard started forward-testing${scorecard.median_alpha_vs_spy !== null ? `, with a median 1-day alpha of ${scorecard.median_alpha_vs_spy >= 0 ? "+" : ""}${scorecard.median_alpha_vs_spy.toFixed(2)}% vs SPY` : ""}. Full per-day history at tapeline.io/scorecard/${t.symbol}.`
          : `Every market day, Tapeline freezes the top 10 composite scores and logs each name's next-day return versus SPY. ${t.symbol} hasn't been in a top-10 cohort yet; the universe-wide history lives at tapeline.io/scorecard.`,
    },
    {
      q: `What does ${t.symbol}'s confidence percentage mean?`,
      a:
        confidence !== null
          ? `${t.symbol} has a ${Math.round(confidence)}% confidence reading, which reflects how complete the data coverage is across the six factor inputs (Trend, Relative Strength, Fundamentals, Smart Money, Macro, Momentum). High confidence (>=85%) means full coverage typical of mega-caps; lower confidence (<55%) means sparse coverage typical of micro-caps, ETFs, or recent IPOs.`
          : `Confidence reflects how complete the data coverage is across the six factor inputs. ${t.symbol}'s reading is pending — the upstream signal updates hourly on this page.`,
    },
    {
      q: `Does Tapeline factor ${t.sector ?? "sector"} dynamics into the ${t.symbol} score?`,
      a:
        `Yes — the Relative Strength factor (20% weight) explicitly compares ${t.symbol}'s performance against both SPY and its sector peers (Mansfield RS calculation). The Macro factor (15%) adds the broader regime overlay (VIX, breadth, 10Y direction). A high score in a hostile macro regime gets dampened by the composite even when the name-specific factors look strong.`,
    },
    {
      q: `How often does the ${t.symbol} Tapeline score update?`,
      a:
        `The composite score recomputes every minute during US market hours (9:30 AM to 4:00 PM ET) on the live data feeds. This page caches each fetch for 30 minutes to keep crawler load light; the interactive product page at tapeline.io/t/${t.symbol} updates in real time. Outside market hours, the score holds at the previous close's value.`,
    },
  ]);

  return (
    <main className="min-h-screen">
      <script {...jsonLdScript(article)} />
      <script {...jsonLdScript(breadcrumbs)} />
      <script {...jsonLdScript(faq)} />
      <MarketingNav />

      <article className="mx-auto max-w-3xl px-4 sm:px-6 py-10">
        <Link href="/blog" className="text-sm text-muted hover:text-fg">
          &larr; All posts
        </Link>

        <header className="mt-6">
          <div className="text-xs uppercase tracking-wider text-subtle">
            Updated {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
            {" · "}
            {t.sector} · Tapeline analysis
          </div>
          <h1 className="mt-3 text-4xl sm:text-5xl font-bold tracking-tight">
            Is {t.symbol} a Buy in 2026? The Tapeline Score Breakdown for {t.name}
          </h1>
          <p className="mt-4 text-lg text-muted leading-relaxed">
            {t.name} — {t.context} — is one of the most-searched tickers on US markets. Most "is {t.symbol} a buy" tools give you a verdict and hide the formula. This page does the opposite: the live Tapeline composite, all six factor sub-scores, the plain-English reason behind today's read, and a link to the public scorecard where every prediction is back-checked vs SPY the next day.
          </p>
        </header>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">{t.symbol}'s Tapeline Score Right Now</h2>
          <div className="mt-4 rounded-2xl border border-border bg-panel/40 p-6">
            <div className="flex items-baseline justify-between gap-6 flex-wrap">
              <div>
                <div className="text-xs uppercase tracking-wider text-subtle">Composite (0–100)</div>
                <div className="mt-1 text-5xl font-bold nums">{fmtScore(composite)}</div>
              </div>
              <div className="text-right">
                <div className="text-xs uppercase tracking-wider text-subtle">Signal</div>
                <div className={`mt-1 text-2xl font-semibold ${signalClass}`}>{signal ?? "—"}</div>
                {confidence !== null && (
                  <div className="mt-1 text-xs text-muted">Confidence {Math.round(confidence)}%</div>
                )}
              </div>
            </div>
            {reason && (
              <p className="mt-5 text-sm text-fg leading-relaxed">
                <span className="text-xs uppercase tracking-wider text-subtle">Why: </span>
                {reason}
              </p>
            )}
            <p className="mt-5 text-xs text-muted">
              Live data from <code className="rounded bg-panel px-1.5 py-0.5">/api/ticker/{t.symbol}</code>. The score refreshes every minute during US market hours; this page caches each fetch for 30 minutes.
            </p>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">What's Driving {t.symbol}'s Score</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            Tapeline's composite is a fixed weighted equation, published on <Link href="/how-it-works" className="text-accent hover:underline">/how-it-works</Link>:
          </p>
          <pre className="mt-4 overflow-x-auto rounded-xl border border-border bg-panel/40 p-5 font-mono text-xs leading-relaxed">
{`score = 0.25 × trend
      + 0.20 × relative_strength
      + 0.15 × fundamentals
      + 0.15 × smart_money
      + 0.15 × macro
      + 0.10 × momentum`}
          </pre>
          <div className="mt-6">
            <FactorRow
              label="Trend"
              factor={data?.breakdown?.trend}
              why="20/50/200-day moving-average stack, slope, and time above the 50DMA. Highest weight (25%) because primary-trend alignment dominates 1-day-to-3-week outcomes."
            />
            <FactorRow
              label="Relative Strength"
              factor={data?.breakdown?.rs}
              why="Mansfield RS vs SPY, sector RS, and 12-1 momentum. Captures whether the name is leading or lagging the broader tape on a multi-week basis."
            />
            <FactorRow
              label="Fundamentals"
              factor={data?.breakdown?.fundamentals}
              why="Revenue growth, operating-margin trend, ROE vs sector median, and Piotroski F-score. The quality filter — confirms the name isn't fundamentally broken."
            />
            <FactorRow
              label="Smart Money"
              factor={data?.breakdown?.smart_money}
              why="SEC Form 4 insider transactions (net 90-day) and Congressional disclosures. Confirmation factor — most useful in confluence with leading factors."
            />
            <FactorRow
              label="Macro"
              factor={data?.breakdown?.macro}
              why="VIX percentile, market breadth, 10Y yield direction, and regime score. Scales the read — same factor configuration in a hostile regime gets a different verdict."
            />
            <FactorRow
              label="Momentum"
              factor={data?.breakdown?.momentum}
              why="20-day rate-of-change, RSI position, and accumulation/distribution. Lowest weight (10%) because it already overlaps with Trend and RS."
            />
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">What "{signal ?? "Pending"}" Means for {t.symbol} Right Now</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">{narrative}</p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The label is descriptive, not prescriptive — Tapeline doesn't say "buy" or "sell" on {t.symbol}. It says <em>here's what six independent signals add up to</em>, and leaves the position-sizing, time-horizon, and tax-situation parts of the decision to you. The labels above are calibrated against the public scorecard's forward-test results, not against an opinion of where the market should be.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">Confidence — Why {t.symbol} Scores {confidence !== null ? `${Math.round(confidence)}%` : "—"}</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">{confidenceText}</p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            Confidence is the column most retail traders skip. It shouldn't be. Two tickers with the same 78 composite carry very different conviction if one is at 92% confidence (full data coverage) and the other is at 51% (sparse). For sizing purposes, confidence is closer to "how much should this read weigh in the portfolio" than the composite alone.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">The Public Scorecard — {t.symbol}'s Track Record</h2>
          {scorecard && scorecard.appearances > 0 ? (
            <>
              <p className="mt-3 text-base text-fg leading-relaxed">
                {t.symbol} has been in Tapeline's top-10 cohort{" "}
                <strong className="text-fg">{scorecard.appearances} time{scorecard.appearances === 1 ? "" : "s"}</strong> since the public scorecard started forward-testing.
                {scorecard.appearances_scored > 0 && (
                  <>
                    {" "}Of those, {scorecard.appearances_scored} have a recorded next-day return vs SPY
                    {scorecard.entries_excluded_outliers > 0 && (
                      <> ({scorecard.entries_excluded_outliers} excluded as vendor-data outliers; methodology on the page)</>
                    )}
                    .
                    {scorecard.median_alpha_vs_spy !== null && (
                      <>
                        {" "}Median 1-day alpha:{" "}
                        <strong className={scorecard.median_alpha_vs_spy > 0 ? "text-up" : "text-down"}>
                          {scorecard.median_alpha_vs_spy >= 0 ? "+" : ""}
                          {scorecard.median_alpha_vs_spy.toFixed(2)}%
                        </strong>
                        {scorecard.hit_rate_beat_spy !== null && (
                          <>. Beat-SPY rate: <strong className="text-fg">{Math.round(scorecard.hit_rate_beat_spy)}%</strong></>
                        )}
                        .
                      </>
                    )}
                  </>
                )}
                {scorecard.best_alpha !== null && scorecard.worst_alpha !== null && (
                  <>
                    {" "}Best single-day alpha:{" "}
                    <span className="text-up">{scorecard.best_alpha >= 0 ? "+" : ""}{scorecard.best_alpha.toFixed(2)}%</span>;
                    worst:{" "}
                    <span className="text-down">{scorecard.worst_alpha >= 0 ? "+" : ""}{scorecard.worst_alpha.toFixed(2)}%</span>.
                  </>
                )}
              </p>
              <p className="mt-3 text-base text-fg leading-relaxed">
                Full per-day history (including every miss) at{" "}
                <Link href={`/scorecard/${t.symbol}`} className="text-accent hover:underline">/scorecard/{t.symbol}</Link>. Sample sizes under 20-30 entries are statistically noisy — treat the median as directional, not as a predicted return.
              </p>
            </>
          ) : (
            <p className="mt-3 text-base text-fg leading-relaxed">
              {t.symbol} hasn't been in a Tapeline top-10 cohort yet, so there's no per-ticker back-check history on the public scorecard. That's not a negative read — only the top-scoring 10 names per session are frozen for back-checking, so the bar for inclusion is high. Today's composite ({fmtScore(composite)}) shows where {t.symbol} currently ranks. The full universe-wide scorecard, including every other ticker that has been frozen, lives at{" "}
              <Link href="/scorecard" className="text-accent hover:underline">/scorecard</Link>.
            </p>
          )}
          <p className="mt-3 text-base text-fg leading-relaxed">
            The scorecard isn't proof the formula will keep working — it's evidence the publisher isn't hiding the misses. That's the part most prosumer scanner tools refuse to do. If you can't see the misses, you can't tell whether a score is signal or marketing.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">Risks to Consider Before Acting on {t.symbol}'s Score</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The Tapeline score summarizes six independent signals into one number — it doesn't know your portfolio, your time horizon, your tax situation, or which other names you're considering at the same risk slot. A high score on {t.symbol} that confirms what other names in your watchlist are already showing isn't the same trade as a high score on a name with no portfolio context.
          </p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The factor breakdown is the part to read carefully. The composite is a summary; the six factors show whether the read is concentrated in one factor (single-source signal, easier to be wrong) or distributed across leading and lagging factors (confluence, higher conviction). Tapeline labels are descriptive — "HIGH CONVICTION", "STRONG SETUP", "CONSTRUCTIVE" — not "BUY" prescriptions. That distinction matters legally and practically.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">Questions about the {t.symbol} score</h2>
          <p className="mt-3 text-sm text-muted">
            FAQ — the same answers are encoded as structured data on this page so search engines can surface them as rich results.
          </p>
          <div className="mt-4 divide-y divide-border/60">
            <details className="group py-4">
              <summary className="flex cursor-pointer items-baseline justify-between gap-4 list-none">
                <h3 className="text-sm font-medium">Does Tapeline factor {t.sector ?? "sector"} dynamics into the {t.symbol} score?</h3>
                <span className="text-muted transition-transform group-open:rotate-45">+</span>
              </summary>
              <p className="mt-2 text-sm text-muted leading-relaxed">
                Yes — the Relative Strength factor (20% weight) explicitly compares {t.symbol}'s performance against both SPY and its sector peers (Mansfield RS calculation). The Macro factor (15%) adds the broader regime overlay (VIX, breadth, 10Y direction). A high score in a hostile macro regime gets dampened by the composite even when the name-specific factors look strong.
              </p>
            </details>
            <details className="group py-4">
              <summary className="flex cursor-pointer items-baseline justify-between gap-4 list-none">
                <h3 className="text-sm font-medium">How often does the {t.symbol} score update?</h3>
                <span className="text-muted transition-transform group-open:rotate-45">+</span>
              </summary>
              <p className="mt-2 text-sm text-muted leading-relaxed">
                The composite recomputes every minute during US market hours on the live feeds. This page caches each fetch for 30 minutes to keep crawler load light; <Link href={`/t/${t.symbol}`} className="text-accent hover:underline">/t/{t.symbol}</Link> updates in real time. Outside market hours, the score holds at the previous close's value.
              </p>
            </details>
            <details className="group py-4">
              <summary className="flex cursor-pointer items-baseline justify-between gap-4 list-none">
                <h3 className="text-sm font-medium">Is the {t.symbol} Tapeline score a buy recommendation?</h3>
                <span className="text-muted transition-transform group-open:rotate-45">+</span>
              </summary>
              <p className="mt-2 text-sm text-muted leading-relaxed">
                No. The label is descriptive (HIGH CONVICTION / STRONG SETUP / CONSTRUCTIVE / NEUTRAL / CAUTION / WEAK), not prescriptive. It summarizes six independent signals into one 0-100 number. Acting on it depends on portfolio, risk tolerance, time horizon, and tax situation Tapeline doesn't know about. See <Link href="/legal/risk" className="text-accent hover:underline">/legal/risk</Link> for the full general-information posture.
              </p>
            </details>
            <details className="group py-4">
              <summary className="flex cursor-pointer items-baseline justify-between gap-4 list-none">
                <h3 className="text-sm font-medium">What does {t.symbol}'s confidence percentage mean?</h3>
                <span className="text-muted transition-transform group-open:rotate-45">+</span>
              </summary>
              <p className="mt-2 text-sm text-muted leading-relaxed">
                {confidenceText}
              </p>
            </details>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">How to Track {t.symbol} Live on Tapeline</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The interactive {t.symbol} page lives at <Link href={`/t/${t.symbol}`} className="text-accent hover:underline">/t/{t.symbol}</Link> — same data, plus a live radar chart, news feed, and watchlist add. The full scanner covering ~2,500 US tickers is at <Link href="/app/scanner" className="text-accent hover:underline">/app/scanner</Link>.
          </p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            Tapeline Free covers the top 20 tickers with a 24-hour data delay — enough to evaluate the methodology, not enough for daily trading. Pro ($24.99/mo billed annually, or $29.99 monthly) unlocks the full universe with live data, watchlist alerts on score moves, and the IPO/earnings calendar. Premium ($39.99/mo annually, $49.99 monthly) adds Congressional trades, recent insider buys (SEC Form 4), and unlimited Telegram alerts. 14-day Premium trial, no card.
          </p>
        </section>

        <div className="mt-16 rounded-2xl border border-accent/30 bg-gradient-to-br from-accent/5 via-panel to-panel p-8">
          <h2 className="text-xl font-semibold tracking-tight">See {t.symbol}'s live score now.</h2>
          <p className="mt-2 text-sm text-muted">
            14-day Premium trial. No credit card. The six-factor formula above runs on {t.symbol} and every other liquid US ticker every minute.
          </p>
          <div className="mt-5 flex flex-wrap gap-3">
            <Link href={`/t/${t.symbol}`} className="btn-accent">
              Open the live {t.symbol} page &rarr;
            </Link>
            <Link href="/signup" className="btn-ghost">
              Try Premium free
            </Link>
            <Link href="/scorecard" className="btn-ghost">
              See the public scorecard
            </Link>
          </div>
        </div>

        <nav className="mt-14 pt-8">
          <div className="text-xs uppercase tracking-wider text-subtle">Other ticker analyses</div>
          <ul className="mt-3 flex flex-wrap gap-2 text-sm">
            {TICKERS.filter((x: TickerPost) => x.symbol !== t.symbol).slice(0, 8).map((x) => (
              <li key={x.symbol}>
                <Link
                  href={`/blog/ticker/${x.symbol}`}
                  className="rounded-md border border-border bg-panel/40 px-3 py-1.5 text-fg hover:border-accent/40 hover:text-accent transition-colors"
                >
                  {x.symbol}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        {/* Lead-magnet email capture — long-form ticker blog pages
            convert better than the bare /t/[symbol] page because the
            reader has already invested attention. Same daily-Top-10
            offer, lower friction than the trial CTA. */}
        <aside className="mt-12 rounded-lg border border-border bg-panel/30 p-6">
          <div className="text-center mb-4">
            <h3 className="text-lg font-semibold text-fg">
              Get the daily Top 10 in your inbox
            </h3>
            <p className="mx-auto mt-2 max-w-md text-sm text-muted leading-relaxed">
              The 10 highest-scoring US tickers each market morning, same
              composite this article uses. No card, unsubscribe in one click.
            </p>
          </div>
          <div className="mx-auto max-w-md">
            <NewsletterCapture source="blog" heading="" sub="" />
          </div>
        </aside>
      </article>

      <MarketingFooter />
    </main>
  );
}
