/**
 * Per-ticker SEO landing pages at /blog/ticker/{SYMBOL}.
 *
 * One template serves 50 posts (manifest at app/blog/ticker/tickers.ts,
 * generated by scripts/generate-ticker-posts.mjs). Each post:
 *   - Targets long-tail queries like "{SYMBOL} stock score 2026" and
 *     "is {SYMBOL} a buy".
 *   - Pulls live score + 6-factor breakdown + plain-English reason from
 *     /api/ticker/{symbol} at request time, with Next.js revalidate
 *     caching so we're not hammering the API on every crawler hit.
 *   - Links into /t/{symbol} for the interactive product surface and
 *     /scorecard for the public back-check.
 *
 * Distinct from /t/[symbol]: that page is the interactive product surface
 * (watchlist add, share, OG card). This page is long-form editorial with
 * scoring methodology context — same data, different SERP intent.
 */
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarketingNav } from "@/components/MarketingNav";
import { MarketingFooter } from "@/components/MarketingFooter";
import { pageMeta } from "@/lib/seo";
import { articleJsonLd, breadcrumbJsonLd, faqJsonLd, jsonLdScript } from "@/lib/jsonld";
import { TICKERS, findTicker, type TickerPost } from "../tickers";

// Refresh per-page live data every 30 minutes. Long-tail SEO pages don't
// need sub-minute freshness; longer cache = fewer API hits on each crawl.
export const revalidate = 1800;

const API_BASE =
  process.env.NEXT_PUBLIC_API_URL ||
  process.env.API_URL ||
  "https://api.tapeline.io";

type FactorEntry = { value: number | null; weight: number; label: string };

type TickerData = {
  symbol: string;
  name: string;
  sector: string | null;
  price: number | null;
  score: number | null;
  signal: string | null;
  confidence_pct: number | null;
  change_pct_1d: number | null;
  change_pct_5d: number | null;
  change_pct_1m: number | null;
  reason: string | null;
  breakdown?: {
    trend?: FactorEntry;
    rs?: FactorEntry;
    fundamentals?: FactorEntry;
    smart_money?: FactorEntry;
    macro?: FactorEntry;
    momentum?: FactorEntry;
  };
};

async function fetchTicker(symbol: string): Promise<TickerData | null> {
  try {
    const res = await fetch(`${API_BASE}/api/ticker/${symbol}`, {
      next: { revalidate: 1800 },
    });
    if (!res.ok) return null;
    return (await res.json()) as TickerData;
  } catch {
    return null;
  }
}

// Build every URL at build time so Google can find them on a normal crawl
// rather than needing a deep-link discovery pass.
export function generateStaticParams() {
  return TICKERS.map((t) => ({ symbol: t.symbol }));
}

export async function generateMetadata({ params }: { params: { symbol: string } }) {
  const t = findTicker(params.symbol);
  if (!t) {
    return pageMeta({
      title: "Ticker not found — Tapeline",
      description: "This per-ticker analysis page no longer exists or has moved.",
      path: `/blog/ticker/${params.symbol}`,
    });
  }
  return pageMeta({
    title: `Is ${t.symbol} a Buy in 2026? The Tapeline Score Breakdown`,
    description:
      `Live Tapeline 6-factor score on ${t.symbol} (${t.name}) — composite, ` +
      `signal label, Trend / Relative Strength / Fundamentals / Smart Money / ` +
      `Macro / Momentum sub-scores, plain-English reason, and the public ` +
      `scorecard's track record. Same formula, every ticker, every day.`,
    path: `/blog/ticker/${t.symbol}`,
    ogType: "article",
    publishedTime: "2026-05-14",
  });
}

const SIGNAL_COLOR: Record<string, string> = {
  "HIGH CONVICTION": "text-up",
  "STRONG SETUP": "text-up",
  "CONSTRUCTIVE": "text-fg",
  "NEUTRAL": "text-muted",
  "CAUTION": "text-yellow-400",
  "WEAK": "text-down",
};

function fmtScore(v: number | null | undefined): string {
  return v === null || v === undefined ? "—" : v.toFixed(1);
}

function fmtFactor(v: number | null | undefined): string {
  return v === null || v === undefined ? "—" : Math.round(v).toString();
}

function FactorRow({ label, factor, why }: { label: string; factor: FactorEntry | undefined; why: string }) {
  const v = factor?.value;
  const weight = factor?.weight ?? 0;
  return (
    <div className="border-t border-border py-4">
      <div className="flex items-baseline justify-between gap-4">
        <div className="text-base font-medium">{label} <span className="text-xs text-muted">· {weight}% weight</span></div>
        <div className="font-mono text-xl font-bold nums">{fmtFactor(v)}</div>
      </div>
      <p className="mt-1 text-sm text-muted leading-relaxed">{why}</p>
    </div>
  );
}

export default async function TickerBlogPost({ params }: { params: { symbol: string } }) {
  const t = findTicker(params.symbol);
  if (!t) notFound();

  const data = await fetchTicker(t.symbol);

  const composite = data?.score ?? null;
  const signal = data?.signal ?? null;
  const reason = data?.reason ?? null;
  const confidence = data?.confidence_pct ?? null;
  const signalClass = signal ? (SIGNAL_COLOR[signal] ?? "text-fg") : "text-muted";

  const articleUrl = `https://tapeline.io/blog/ticker/${t.symbol}`;
  const article = articleJsonLd({
    title: `Is ${t.symbol} a Buy in 2026? The Tapeline Score Breakdown`,
    description: `Live Tapeline 6-factor score on ${t.symbol} (${t.name}) with full sub-score breakdown and methodology.`,
    url: articleUrl,
    publishedAt: "2026-05-14T00:00:00Z",
    author: "Tapeline",
  });
  const breadcrumbs = breadcrumbJsonLd([
    { name: "Tapeline", url: "https://tapeline.io/" },
    { name: "Blog", url: "https://tapeline.io/blog" },
    { name: `${t.symbol} score`, url: articleUrl },
  ]);
  const faq = faqJsonLd([
    {
      q: `What is ${t.symbol}'s Tapeline score?`,
      a:
        composite !== null
          ? `${t.symbol} (${t.name}) currently scores ${composite.toFixed(1)} out of 100 on Tapeline's 6-factor composite — signal label "${signal ?? "—"}". The score updates every minute during US market hours.`
          : `${t.symbol} (${t.name}) is in Tapeline's scoring universe. The composite score is computed from six weighted factors and updates every minute during US market hours.`,
    },
    {
      q: `How is the ${t.symbol} score calculated?`,
      a:
        `Tapeline uses one fixed formula for every ticker: 25% trend + 20% relative strength + 15% fundamentals + 15% smart money + 15% macro + 10% momentum. The weights are public, versioned, and don't change without a changelog entry.`,
    },
    {
      q: `Is the ${t.symbol} Tapeline score a buy recommendation?`,
      a:
        `No. The score is descriptive, not prescriptive — it summarizes six independent signals into one 0-100 number. Acting on it depends on portfolio, risk tolerance, time horizon, and tax situation Tapeline doesn't know about.`,
    },
    {
      q: `Where can I see Tapeline's track record on ${t.symbol}?`,
      a:
        `Every market day, Tapeline freezes the top 10 composite scores and logs each name's next-day return versus SPY. The full history — including misses — lives on the public scorecard at tapeline.io/scorecard with no survivor-bias filtering.`,
    },
  ]);

  return (
    <main className="min-h-screen">
      <script {...jsonLdScript(article)} />
      <script {...jsonLdScript(breadcrumbs)} />
      <script {...jsonLdScript(faq)} />
      <MarketingNav />

      <article className="mx-auto max-w-3xl px-4 sm:px-6 py-16">
        <Link href="/blog" className="text-sm text-muted hover:text-fg">
          &larr; All posts
        </Link>

        <header className="mt-6">
          <div className="text-xs uppercase tracking-wider text-subtle">
            Updated {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
            {" · "}
            {t.sector} · Tapeline analysis
          </div>
          <h1 className="mt-3 text-4xl sm:text-5xl font-bold tracking-tight">
            Is {t.symbol} a Buy in 2026? The Tapeline Score Breakdown for {t.name}
          </h1>
          <p className="mt-4 text-lg text-muted leading-relaxed">
            {t.name} — {t.context} — is one of the most-searched tickers on US markets. Most "is {t.symbol} a buy" tools give you a verdict and hide the formula. This page does the opposite: the live Tapeline composite, all six factor sub-scores, the plain-English reason behind today's read, and a link to the public scorecard where every prediction is back-checked vs SPY the next day.
          </p>
        </header>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">{t.symbol}'s Tapeline Score Right Now</h2>
          <div className="mt-4 rounded-2xl border border-border bg-panel/40 p-6">
            <div className="flex items-baseline justify-between gap-6 flex-wrap">
              <div>
                <div className="text-xs uppercase tracking-wider text-subtle">Composite (0–100)</div>
                <div className="mt-1 text-5xl font-bold nums">{fmtScore(composite)}</div>
              </div>
              <div className="text-right">
                <div className="text-xs uppercase tracking-wider text-subtle">Signal</div>
                <div className={`mt-1 text-2xl font-semibold ${signalClass}`}>{signal ?? "—"}</div>
                {confidence !== null && (
                  <div className="mt-1 text-xs text-muted">Confidence {Math.round(confidence)}%</div>
                )}
              </div>
            </div>
            {reason && (
              <p className="mt-5 text-sm text-fg leading-relaxed">
                <span className="text-xs uppercase tracking-wider text-subtle">Why: </span>
                {reason}
              </p>
            )}
            <p className="mt-5 text-xs text-muted">
              Live data from <code className="rounded bg-panel px-1.5 py-0.5">/api/ticker/{t.symbol}</code>. The score refreshes every minute during US market hours; this page caches each fetch for 30 minutes.
            </p>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">What's Driving {t.symbol}'s Score</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            Tapeline's composite is a fixed weighted equation, published on <Link href="/how-it-works" className="text-accent hover:underline">/how-it-works</Link>:
          </p>
          <pre className="mt-4 overflow-x-auto rounded-xl border border-border bg-panel/40 p-5 font-mono text-xs leading-relaxed">
{`score = 0.25 × trend
      + 0.20 × relative_strength
      + 0.15 × fundamentals
      + 0.15 × smart_money
      + 0.15 × macro
      + 0.10 × momentum`}
          </pre>
          <div className="mt-6">
            <FactorRow
              label="Trend"
              factor={data?.breakdown?.trend}
              why="20/50/200-day moving-average stack, slope, and time above the 50DMA. Highest weight (25%) because primary-trend alignment dominates 1-day-to-3-week outcomes."
            />
            <FactorRow
              label="Relative Strength"
              factor={data?.breakdown?.rs}
              why="Mansfield RS vs SPY, sector RS, and 12-1 momentum. Captures whether the name is leading or lagging the broader tape on a multi-week basis."
            />
            <FactorRow
              label="Fundamentals"
              factor={data?.breakdown?.fundamentals}
              why="Revenue growth, operating-margin trend, ROE vs sector median, and Piotroski F-score. The quality filter — confirms the name isn't fundamentally broken."
            />
            <FactorRow
              label="Smart Money"
              factor={data?.breakdown?.smart_money}
              why="Form 4 insider transactions (net 90-day), elite 13F holdings (8 curated managers), and Congressional disclosures. Confirmation factor — most useful in confluence with leading factors."
            />
            <FactorRow
              label="Macro"
              factor={data?.breakdown?.macro}
              why="VIX percentile, market breadth, 10Y yield direction, and regime score. Scales the read — same factor configuration in a hostile regime gets a different verdict."
            />
            <FactorRow
              label="Momentum"
              factor={data?.breakdown?.momentum}
              why="20-day rate-of-change, RSI position, and accumulation/distribution. Lowest weight (10%) because it already overlaps with Trend and RS."
            />
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">The Public Scorecard: Does {t.symbol}'s Read Hold Up?</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            Every market day, Tapeline freezes the top 10 composite scores at the close. The next day, each pick's actual return is logged against SPY. Wins are recorded, misses are recorded, nothing gets quietly removed. The full track record is at <Link href="/scorecard" className="text-accent hover:underline">/scorecard</Link>, with a per-ticker history if {t.symbol} has ever surfaced in a top-10 cohort.
          </p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The scorecard isn't proof the formula will keep working — it's evidence the publisher isn't hiding the misses. That's the part most prosumer scanner tools refuse to do. If you can't see the misses, you can't tell whether a score is signal or marketing.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">Risks to Consider Before Acting on {t.symbol}'s Score</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The Tapeline score summarizes six independent signals into one number — it doesn't know your portfolio, your time horizon, your tax situation, or which other names you're considering at the same risk slot. A high score on {t.symbol} that confirms what other names in your watchlist are already showing isn't the same trade as a high score on a name with no portfolio context.
          </p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The factor breakdown is the part to read carefully. The composite is a summary; the six factors show whether the read is concentrated in one factor (single-source signal, easier to be wrong) or distributed across leading and lagging factors (confluence, higher conviction). Tapeline labels are descriptive — "HIGH CONVICTION", "STRONG SETUP", "CONSTRUCTIVE" — not "BUY" prescriptions. That distinction matters legally and practically.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">How to Track {t.symbol} Live on Tapeline</h2>
          <p className="mt-3 text-base text-fg leading-relaxed">
            The interactive {t.symbol} page lives at <Link href={`/t/${t.symbol}`} className="text-accent hover:underline">/t/{t.symbol}</Link> — same data, plus a live radar chart, news feed, and watchlist add. The full scanner covering ~2,500 US tickers is at <Link href="/app/scanner" className="text-accent hover:underline">/app/scanner</Link>.
          </p>
          <p className="mt-3 text-base text-fg leading-relaxed">
            Tapeline Free covers the top 20 tickers with a 24-hour data delay — enough to evaluate the methodology, not enough for daily trading. Pro ($24.99/mo billed annually, or $29.99 monthly) unlocks the full universe with live data, watchlist alerts on score moves, and the IPO/earnings calendar. Premium ($39.99/mo annually, $49.99 monthly) adds Congressional trades, elite 13F holdings, and unlimited Telegram alerts. 14-day Premium trial, no card.
          </p>
        </section>

        <div className="mt-16 rounded-2xl border border-accent/30 bg-gradient-to-br from-accent/5 via-panel to-panel p-8">
          <h2 className="text-xl font-semibold tracking-tight">See {t.symbol}'s live score now.</h2>
          <p className="mt-2 text-sm text-muted">
            14-day Premium trial. No credit card. The six-factor formula above runs on {t.symbol} and every other liquid US ticker every minute.
          </p>
          <div className="mt-5 flex flex-wrap gap-3">
            <Link href={`/t/${t.symbol}`} className="btn-accent">
              Open the live {t.symbol} page &rarr;
            </Link>
            <Link href="/signup" className="btn-ghost">
              Start 14-day trial
            </Link>
            <Link href="/scorecard" className="btn-ghost">
              See the public scorecard
            </Link>
          </div>
        </div>

        <nav className="mt-14 border-t border-border pt-8">
          <div className="text-xs uppercase tracking-wider text-subtle">Other ticker analyses</div>
          <ul className="mt-3 flex flex-wrap gap-2 text-sm">
            {TICKERS.filter((x: TickerPost) => x.symbol !== t.symbol).slice(0, 8).map((x) => (
              <li key={x.symbol}>
                <Link
                  href={`/blog/ticker/${x.symbol}`}
                  className="rounded-md border border-border bg-panel/40 px-3 py-1.5 text-fg hover:border-accent/40 hover:text-accent transition-colors"
                >
                  {x.symbol}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </article>

      <MarketingFooter />
    </main>
  );
}
