import Link from "next/link";
import { MarketingNav } from "@/components/MarketingNav";
import { MarketingFooter } from "@/components/MarketingFooter";
import { POSTS } from "./posts";
import { pageMeta } from "@/lib/seo";
import { blogIndexJsonLd, breadcrumbJsonLd, jsonLdScript } from "@/lib/jsonld";

const baseMeta = pageMeta({
  title: "Tapeline Blog — Notes from Building a Quantitative Stock Scanner",
  description:
    "Methodology, market commentary, and notes from building Tapeline. Posts on stock scanner evaluation, quantitative signals, transparent scoring, and active scanning vs static screening.",
  path: "/blog",
});

// Add the RSS alternate alongside the canonical generated by pageMeta().
export const metadata = {
  ...baseMeta,
  alternates: {
    ...baseMeta.alternates,
    types: { "application/rss+xml": "https://tapeline.io/blog/rss.xml" },
  },
};

export default function BlogIndex() {
  // Newest first.
  const sorted = [...POSTS].sort(
    (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );

  // Blog + ItemList schema replaces the un-typed JSON-LD this route used to
  // emit. Posts feed into both BlogPosting children and ItemList ranking.
  const blogGraph = blogIndexJsonLd({ posts: sorted });
  const breadcrumbs = breadcrumbJsonLd([
    { name: "Tapeline", url: "https://tapeline.io/" },
    { name: "Blog", url: "https://tapeline.io/blog" },
  ]);

  return (
    <main className="min-h-screen">
      {blogGraph.map((g, i) => (
        <script key={`blogld-${i}`} {...jsonLdScript(g)} />
      ))}
      <script {...jsonLdScript(breadcrumbs)} />
      <MarketingNav />

      <section className="mx-auto max-w-3xl px-4 sm:px-6 py-16">
        <p className="eyebrow">Blog</p>
        <h1 className="mt-3 text-4xl sm:text-5xl font-bold tracking-tight">Notes from building.</h1>
        <p className="mt-4 text-lg text-muted">
          Methodology, market commentary, and occasional rants about scanner pricing.
          Posts are short. Newest first. <a href="/blog/rss.xml" className="text-accent hover:underline">RSS</a>.
        </p>

        <div className="mt-12 divide-y divide-border border-y border-border">
          {sorted.map((p) => (
            <article key={p.slug} className="py-6">
              <Link href={`/blog/${p.slug}`} className="group block">
                <div className="text-xs uppercase tracking-wider text-subtle">
                  {new Date(p.publishedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
                  {" · "}
                  {p.author}
                </div>
                <h2 className="mt-2 text-2xl font-semibold tracking-tight group-hover:text-accent transition-colors">
                  {p.title}
                </h2>
                <p className="mt-2 text-sm text-muted leading-relaxed">{p.excerpt}</p>
                <span className="mt-3 inline-block text-sm text-accent group-hover:underline">
                  Read &rarr;
                </span>
              </Link>
            </article>
          ))}
        </div>

        {sorted.length === 0 && (
          <div className="mt-12 rounded-xl border border-border bg-panel p-8 text-center text-muted">
            No posts yet. Subscribe-by-RSS coming once the corpus is bigger.
          </div>
        )}
      </section>

      <MarketingFooter />
    </main>
  );
}
