/**
 * The browser half of the Meta conversion pair must agree with the server half.
 *
 * WHY THESE FIXTURES ARE HARDCODED
 * --------------------------------
 * The three expected ids below were generated by running the REAL Python
 * implementation, not by copying this module's own output:
 *
 *     python -c "from app.services.meta_capi import event_id_for; \
 *                print(event_id_for('signup', 'usr_abc123'))"
 *
 * That is the entire value of this file. A test that derived the expectation
 * from `metaEventId` itself would pass while both sides drifted together, and
 * drift here is expensive: Meta de-duplicates on (event_name, event_id), so a
 * mismatch double-counts every registration once the Conversions API token is
 * set. Cost-per-registration is the pre-committed kill criterion for the live
 * paid burst (docs/META_BURST_BUILD.md §7) — a 2x overcount would make a
 * failing test look like it was clearing the bar while real money kept flowing.
 *
 * If someone changes the derivation in `meta_capi.event_id_for`, this suite
 * fails, which is correct: the two are one contract in two languages.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import {
  metaEventId,
  trackMetaCompleteRegistration,
  trackMetaLead,
} from "@/lib/metaConversions";

vi.mock("@/lib/trackers", () => ({
  trackerEnabled: { meta: true },
}));

/** Generated by backend/app/services/meta_capi.py::event_id_for. */
const PYTHON_FIXTURES: ReadonlyArray<[string, string]> = [
  ["usr_abc123", "signup.6988ba61631398f78c750227c919a48a"],
  ["42", "signup.dea251a5c36a7f58a4b8e23a716ce358"],
  [
    "e3b0c442-98fc-1c14-9afb-f4c8996fb924",
    "signup.4d5d504d7198c6b02eeb6f2d4dd0c121",
  ],
];

describe("metaEventId matches the Python implementation", () => {
  it.each(PYTHON_FIXTURES)("derives %s identically", async (uid, expected) => {
    await expect(metaEventId("signup", uid)).resolves.toBe(expected);
  });

  it("is 32 hex chars after the kind prefix", async () => {
    const id = await metaEventId("signup", "usr_abc123");
    expect(id).toMatch(/^signup\.[0-9a-f]{32}$/);
  });

  it("varies with the kind, so signup and trial never collide", async () => {
    const a = await metaEventId("signup", "same-id");
    const b = await metaEventId("trial", "same-id");
    expect(a).not.toBe(b);
  });
});

describe("trackMetaCompleteRegistration", () => {
  afterEach(() => {
    delete (window as unknown as { fbq?: unknown }).fbq;
    vi.restoreAllMocks();
  });

  it("sends CompleteRegistration with the deduplicating eventID", async () => {
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;

    const sent = await trackMetaCompleteRegistration({ userId: "usr_abc123" });

    expect(sent).toBe("signup.6988ba61631398f78c750227c919a48a");
    expect(fbq).toHaveBeenCalledWith(
      "track",
      "CompleteRegistration",
      { content_name: "email" },
      { eventID: "signup.6988ba61631398f78c750227c919a48a" },
    );
  });

  it("accepts a numeric user id, matching the server's str() coercion", async () => {
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;

    const sent = await trackMetaCompleteRegistration({ userId: 42 });

    expect(sent).toBe("signup.dea251a5c36a7f58a4b8e23a716ce358");
  });

  it("sends NO personal data — no address, no advanced-matching keys", async () => {
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;

    await trackMetaCompleteRegistration({
      userId: "usr_abc123",
      method: "email",
    });

    const [, , params, options] = fbq.mock.calls[0];

    // `content_name: "email"` is the SIGNUP METHOD ("email" vs "google") and
    // mirrors the server's custom_data exactly. It is not an address, so this
    // asserts the real invariant instead of banning the substring: the params
    // carry that one key and nothing else, and the options carry only eventID.
    expect(Object.keys(params as object)).toEqual(["content_name"]);
    expect(Object.keys(options as object)).toEqual(["eventID"]);

    // Meta's advanced-matching keys, none of which we ever populate here.
    const payload = JSON.stringify(fbq.mock.calls[0]);
    for (const key of ["em", "ph", "fn", "ln", "ct", "st", "zp", "country"]) {
      expect(payload).not.toContain(`"${key}"`);
    }
    // And nothing that could be an actual address.
    expect(payload).not.toContain("@");
  });

  it("no-ops silently when the pixel is blocked or absent", async () => {
    // No window.fbq at all — the common case for this audience.
    await expect(
      trackMetaCompleteRegistration({ userId: "usr_abc123" }),
    ).resolves.toBeNull();
  });

  it("never throws when the pixel stub throws", async () => {
    (window as unknown as { fbq: unknown }).fbq = () => {
      throw new Error("blocked by extension");
    };

    await expect(
      trackMetaCompleteRegistration({ userId: "usr_abc123" }),
    ).resolves.toBeNull();
  });
});

/**
 * `Lead` — the free daily-email subscription (decision "L1", 2026-09-19).
 *
 * Browser ONLY, by decision rather than by omission: the live privacy policy
 * covers sending Meta a hashed email on signup / trial / charge, and a
 * newsletter subscription is none of those. So unlike CompleteRegistration
 * there is no server copy to dedupe against and no stable account id to derive
 * from — the id is random per subscription, and the payload must carry nothing
 * that could identify the subscriber. These tests pin exactly that.
 */
describe("trackMetaLead", () => {
  afterEach(() => {
    delete (window as unknown as { fbq?: unknown }).fbq;
    window.history.replaceState({}, "", "/");
    vi.restoreAllMocks();
  });

  it("sends Lead with empty params and only an eventID", async () => {
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;
    window.history.replaceState({}, "", "/daily-picks");

    const sent = await trackMetaLead();

    expect(sent).toMatch(/^lead\.[0-9a-f]{32}$/);
    expect(fbq).toHaveBeenCalledTimes(1);
    expect(fbq).toHaveBeenCalledWith("track", "Lead", {}, { eventID: sent });
  });

  it("sends NO personal data — no address, no advanced-matching keys", async () => {
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;

    await trackMetaLead();

    expect(fbq.mock.calls[0]).toHaveLength(4);
    const [, , params, options] = fbq.mock.calls[0];
    expect(params).toEqual({});
    expect(Object.keys(options as object)).toEqual(["eventID"]);

    const payload = JSON.stringify(fbq.mock.calls[0]);
    for (const key of ["em", "ph", "fn", "ln", "ct", "st", "zp", "country", "external_id"]) {
      expect(payload).not.toContain(`"${key}"`);
    }
    expect(payload).not.toContain("@");
  });

  it("uses a fresh id for each subscription, so two people are never merged into one", async () => {
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;

    const a = await trackMetaLead();
    const b = await trackMetaLead();

    expect(a).not.toBeNull();
    expect(b).not.toBeNull();
    expect(a).not.toBe(b);
  });

  it("never fires on the signed-in app, even if the pixel is already in the document", async () => {
    // fbevents.js survives a client-side navigation from a marketing page into
    // /app (see MetaPixel.tsx, "HONEST LIMIT"). Its beacon carries the full URL,
    // so a Lead sent from /app/ticker/X would tell Meta which ticker was open.
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;
    window.history.replaceState({}, "", "/app/ticker/NVDA");

    await expect(trackMetaLead()).resolves.toBeNull();
    expect(fbq).not.toHaveBeenCalled();
  });

  it("no-ops silently when the pixel is blocked or absent", async () => {
    await expect(trackMetaLead()).resolves.toBeNull();
  });

  it("never throws when the pixel stub throws", async () => {
    (window as unknown as { fbq: unknown }).fbq = () => {
      throw new Error("blocked by extension");
    };

    await expect(trackMetaLead()).resolves.toBeNull();
  });

  it("sends nothing when the pixel is switched off for this build", async () => {
    vi.resetModules();
    vi.doMock("@/lib/trackers", () => ({ trackerEnabled: { meta: false } }));
    const fbq = vi.fn();
    (window as unknown as { fbq: unknown }).fbq = fbq;

    try {
      const mod = await import("@/lib/metaConversions");
      await expect(mod.trackMetaLead()).resolves.toBeNull();
      expect(fbq).not.toHaveBeenCalled();
    } finally {
      vi.doUnmock("@/lib/trackers");
    }
  });
});
