/**
 * Browser half of the Meta conversion pair.
 *
 * WHY THIS EXISTS
 * ---------------
 * `backend/app/services/meta_capi.py` has always described `event_id_for` as
 * "Deterministic `event_id` shared by the browser pixel and this module" — the
 * design assumed a browser counterpart from the start. It was never written.
 * The consequence showed up only once the burst went live: Events Manager held
 * exactly one event for the dataset, `PageView`, while the ad set optimised
 * toward `CompleteRegistration`. Meta was bidding toward a conversion it had no
 * examples of, on a fresh account already fighting Learning Limited.
 *
 * The server half cannot cover for that today because it is gated on a
 * Conversions API token that is not set. This module makes the browser send the
 * event now, and — because the id is derived the same way on both sides — makes
 * the two collapse into ONE conversion the moment that token lands.
 *
 * DEDUPLICATION IS THE WHOLE POINT, SO GET IT EXACTLY RIGHT
 * ---------------------------------------------------------
 * Meta de-duplicates on the pair (`event_name`, `event_id`) within ~48h. The id
 * here must byte-for-byte match `meta_capi.event_id_for("signup", user_id)`:
 *
 *     sha256("tapeline:" + kind + ":" + stable_id).hexdigest()[:32]
 *     prefixed with `kind + "."`
 *
 * If it ever drifts, registrations DOUBLE-COUNT once the CAPI token is set.
 * That is not a cosmetic reporting bug: cost-per-registration is the pre-
 * committed kill criterion for the paid burst (`docs/META_BURST_BUILD.md` §7),
 * so a 2x overcount would make a failing test look like it was clearing the bar
 * and keep real money flowing into it. `__tests__/metaConversions.test.ts` pins
 * the format against fixtures generated by the Python implementation itself.
 *
 * WHY NOT JUST PASS THE ID FROM THE SERVER
 * -----------------------------------------
 * Because deriving it from a stable id is what lets the two sides agree without
 * passing anything between them — including on paths where no response body is
 * available. Keeping the derivation is also what keeps the hash a hash: a Stripe
 * subscription id is never exposed in a browser payload.
 *
 * WHAT THIS DELIBERATELY DOES NOT SEND
 * ------------------------------------
 * No email, no name, no advanced-matching object. Match quality on the browser
 * side is whatever `_fbc`/`_fbp` the pixel already set for itself. Everything
 * identifying stays server-side, hashed, where the privacy policy says it is.
 */

import { trackerEnabled } from "./trackers";

type FbqFn = (
  action: string,
  event: string,
  params?: Record<string, unknown>,
  options?: { eventID?: string },
) => void;

/** Mirrors `meta_capi.event_id_for`. Async because SubtleCrypto is async. */
export async function metaEventId(
  kind: string,
  stableId: string,
): Promise<string | null> {
  // SubtleCrypto is unavailable in insecure contexts and in some embedded
  // webviews. No id means no safe way to dedupe, and sending an un-deduped
  // conversion is worse than sending none — so bail rather than guess.
  const subtle =
    typeof globalThis.crypto !== "undefined" ? globalThis.crypto.subtle : undefined;
  if (!subtle) return null;

  const data = new TextEncoder().encode(`tapeline:${kind}:${stableId}`);
  const digest = await subtle.digest("SHA-256", data);
  const hex = Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
  return `${kind}.${hex.slice(0, 32)}`;
}

/**
 * Fire `CompleteRegistration` for a freshly created account.
 *
 * Returns the id actually sent, or null when nothing was sent — which is the
 * common case and never an error: the pixel is off in most builds, and this
 * audience blocks `fbevents.js` heavily. Signup must not care either way, so
 * every failure path here is silent.
 */
export async function trackMetaCompleteRegistration(opts: {
  userId: string | number;
  method?: string;
}): Promise<string | null> {
  if (!trackerEnabled.meta) return null;
  if (typeof window === "undefined") return null;

  const fbq = (window as unknown as { fbq?: FbqFn }).fbq;
  if (typeof fbq !== "function") return null;

  const eventID = await metaEventId("signup", String(opts.userId));
  if (!eventID) return null;

  try {
    fbq(
      "track",
      "CompleteRegistration",
      // Matches the server's `custom_data={"content_name": method}` so the two
      // copies of the event describe themselves identically.
      { content_name: opts.method ?? "email" },
      { eventID },
    );
  } catch {
    // A blocked or stubbed pixel can throw. Never let it reach signup.
    return null;
  }
  return eventID;
}
